# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd WebApplication1
      dir
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/WebApplication1.csproj'
    workingDirectory: 'WebApplication1'
- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: 'WebApplication1.csproj'
    arguments: "-c Release -o $(Build.ArtifactStagingDirectory)/drop"
    workingDirectory: 'WebApplication1'
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: "Publish drop"