# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mygroup


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo $(name)
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: 'specific'
    project: 'PublishDemo'
    pipeline: 'matizaj.PublishDemo'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    downloadPath: '$(System.DefaultWorkingDirectory)/down'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)/resources'
  inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/down/drop/WebApplication1'
      Contents: appsettings.json
      TargetFolder: '$(System.DefaultWorkingDirectory)/resources'
